docs: [PATCHED] When hosted with another default language, all other language links break
2 - When hosted with another default language, all other language links break:
Reproduce:

Deploy wikiless with DEFAULT_LANG="DE" or any other.
Open any wiki page (like for example wiki/United_Nations?lang=de)
Switch to another language
Result:
Error: Cannot GET /wiki/United_Nations


Commit: https://github.com/Metastem/Wikiless/issues/161

Signed-off-by: Jeyso215 <114549769+Jeyso215@users.noreply.github.com>